-- ============================================================================
-- IBM i Query Runner - Database Schema
-- Index Creation Script
-- ============================================================================
--
-- Run this script after creating tables (01_create_tables.sql)
--
-- ============================================================================

-- Indexes for QRYRUN_USERS
CREATE INDEX USERS_LOGIN_IDX ON QRYRUN_USERS(USER_ID, IS_ADMIN);

-- Indexes for QRYRUN_QUERY_SETS
CREATE INDEX QSET_ACTIVE_IDX ON QRYRUN_QUERY_SETS(IS_ACTIVE, CREATED_AT);
CREATE INDEX QSET_USER_IDX ON QRYRUN_QUERY_SETS(SOURCE_USER_PROFILE);

-- Indexes for QRYRUN_QUERIES
CREATE INDEX QUERY_SET_IDX ON QRYRUN_QUERIES(SET_ID, IS_ACTIVE, SEQUENCE_NUM);
CREATE INDEX QUERY_HASH_IDX ON QRYRUN_QUERIES(SET_ID, QUERY_HASH);
CREATE INDEX QUERY_CACHE_KEY_IDX ON QRYRUN_QUERIES(PLAN_CACHE_KEY);

-- Indexes for QRYRUN_SET_REFRESH_LOG
CREATE INDEX REFRESH_SET_IDX ON QRYRUN_SET_REFRESH_LOG(SET_ID, REFRESHED_AT DESC);

-- Indexes for QRYRUN_TEST_RUNS
CREATE INDEX RUN_SET_IDX ON QRYRUN_TEST_RUNS(SET_ID, CREATED_AT DESC);
CREATE INDEX RUN_STATUS_IDX ON QRYRUN_TEST_RUNS(STATUS, CREATED_AT DESC);

-- Indexes for QRYRUN_EXECUTIONS
CREATE INDEX EXEC_RUN_IDX ON QRYRUN_EXECUTIONS(RUN_ID, QUERY_ID, ITERATION_NUM);
CREATE INDEX EXEC_QUERY_IDX ON QRYRUN_EXECUTIONS(QUERY_ID, STATUS);
CREATE INDEX EXEC_TIME_IDX ON QRYRUN_EXECUTIONS(START_TIME);

-- Indexes for QRYRUN_METRICS
CREATE INDEX METRIC_EXEC_IDX ON QRYRUN_METRICS(EXECUTION_ID);

-- Indexes for QRYRUN_COMPARISONS
CREATE INDEX COMP_RUNS_IDX ON QRYRUN_COMPARISONS(BASELINE_RUN_ID, COMPARISON_RUN_ID);

-- Indexes for QRYRUN_COMPARISON_DETAILS
CREATE INDEX DETAIL_COMP_IDX ON QRYRUN_COMPARISON_DETAILS(COMPARISON_ID, STATUS);
CREATE INDEX DETAIL_QUERY_IDX ON QRYRUN_COMPARISON_DETAILS(QUERY_ID);

-- Success message
SELECT 'All indexes created successfully!' AS MESSAGE FROM SYSIBM.SYSDUMMY1;