-- ============================================================================
-- IBM i Query Runner - Database Schema
-- View Creation Script
-- ============================================================================
--
-- Run this script after creating tables and indexes
--
-- ============================================================================

-- View 1: V_QUERY_SET_SUMMARY
-- Summary view of query sets with statistics
CREATE VIEW V_QUERY_SET_SUMMARY AS
SELECT 
    QS.SET_ID,
    QS.SET_NAME,
    QS.SET_DESCRIPTION,
    QS.SOURCE_USER_PROFILE,
    QS.CREATED_BY,
    QS.CREATED_AT,
    QS.LAST_REFRESHED,
    QS.IS_ACTIVE,
    QS.QUERY_COUNT,
    COUNT(DISTINCT TR.RUN_ID) AS TOTAL_RUNS,
    MAX(TR.COMPLETED_AT) AS LAST_RUN_DATE
FROM QRYRUN_QUERY_SETS QS
LEFT JOIN QRYRUN_TEST_RUNS TR ON QS.SET_ID = TR.SET_ID
GROUP BY 
    QS.SET_ID, QS.SET_NAME, QS.SET_DESCRIPTION, 
    QS.SOURCE_USER_PROFILE, QS.CREATED_BY, QS.CREATED_AT,
    QS.LAST_REFRESHED, QS.IS_ACTIVE, QS.QUERY_COUNT;

LABEL ON TABLE V_QUERY_SET_SUMMARY IS 'Query Set Summary View';

-- View 2: V_TEST_RUN_SUMMARY
-- Summary view of test runs with execution statistics
CREATE VIEW V_TEST_RUN_SUMMARY AS
SELECT 
    TR.RUN_ID,
    TR.RUN_NAME,
    TR.SET_ID,
    QS.SET_NAME,
    TR.STATUS,
    TR.CREATED_BY,
    TR.CREATED_AT,
    TR.STARTED_AT,
    TR.COMPLETED_AT,
    TR.ITERATION_COUNT,
    TR.METRICS_LEVEL,
    TR.TOTAL_QUERIES,
    TR.SUCCESSFUL_QUERIES,
    TR.FAILED_QUERIES,
    TR.TOTAL_EXECUTIONS,
    TR.AVG_DURATION_MS,
    CASE 
        WHEN TR.COMPLETED_AT IS NOT NULL AND TR.STARTED_AT IS NOT NULL
        THEN TIMESTAMPDIFF(2, CHAR(TR.COMPLETED_AT - TR.STARTED_AT))
        ELSE NULL
    END AS TOTAL_RUNTIME_SECONDS
FROM QRYRUN_TEST_RUNS TR
JOIN QRYRUN_QUERY_SETS QS ON TR.SET_ID = QS.SET_ID;

LABEL ON TABLE V_TEST_RUN_SUMMARY IS 'Test Run Summary View';

-- View 3: V_QUERY_EXECUTION_STATS
-- Aggregated execution statistics per query
CREATE VIEW V_QUERY_EXECUTION_STATS AS
SELECT 
    E.QUERY_ID,
    E.RUN_ID,
    Q.QUERY_NAME,
    Q.SET_ID,
    COUNT(*) AS EXECUTION_COUNT,
    AVG(E.DURATION_MS) AS AVG_DURATION_MS,
    MIN(E.DURATION_MS) AS MIN_DURATION_MS,
    MAX(E.DURATION_MS) AS MAX_DURATION_MS,
    STDDEV(E.DURATION_MS) AS STDDEV_DURATION_MS,
    SUM(CASE WHEN E.STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    SUM(CASE WHEN E.STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILURE_COUNT,
    SUM(E.ROWS_RETURNED) AS TOTAL_ROWS_RETURNED,
    SUM(E.ROWS_AFFECTED) AS TOTAL_ROWS_AFFECTED
FROM QRYRUN_EXECUTIONS E
JOIN QRYRUN_QUERIES Q ON E.QUERY_ID = Q.QUERY_ID
WHERE E.STATUS IN ('SUCCESS', 'FAILED')
GROUP BY E.QUERY_ID, E.RUN_ID, Q.QUERY_NAME, Q.SET_ID;

LABEL ON TABLE V_QUERY_EXECUTION_STATS IS 'Query Execution Statistics View';

-- Success message
SELECT 'All views created successfully!' AS MESSAGE FROM SYSIBM.SYSDUMMY1;